//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrayCorp.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        public int PROD_ID { get; set; }
        public string PROD_NOME { get; set; }
        public Nullable<int> PROD_ESTOQUE { get; set; }
        public Nullable<decimal> PROD_VALOR { get; set; }
    }
}
